version: '3'

services:
  mc-query:
    image: lunchbox-racing/mcstat:latest
    environment:
      - SERVER=ip or hostname
      - WEBHOOK_URL=your discord webhook url
    restart: unless-stopped
    
